import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { cleanPerson, anonymousPerson, relationshipRepository, relationshipMessages } from '../src/services/buer-relationships.js';
import { loadRelationshipContext, validateRelationshipSelection } from '../api/relationship-context.mjs';
import { validateConversation } from '../api/chat.mjs';
import { calculateHumanDesign } from '../human-design-engine.js';
import { createHumanDesignProfileSnapshot } from '../src/engine/profile-snapshot.js';
import { installNodeFileFetch } from '../api/node-file-fetch.mjs';
installNodeFileFetch();
const A='00000000-0000-4000-a000-000000000001', B='00000000-0000-4000-a000-000000000002';
const me='00000000-0000-4000-b000-000000000001', wife='00000000-0000-4000-b000-000000000002', other='00000000-0000-4000-b000-000000000003';
const thread='00000000-0000-4000-c000-000000000001';
const person=(self=false)=>({nickname:self?'Me':'Partner',relationship:self?'Self':'Partner',is_self:self,source:self?'self':'permission',birth:{certainty:'unknown',date:'',time:'',timezone:'Asia/Shanghai',location:''},chart:null,notes:'private observation'});
test('long relationship histories stay within API bounds while preserving the latest question',()=>{
 const history=Array.from({length:40},(_,i)=>({role:i%2?'assistant':'user',content:'x'.repeat(6000)}));
 const messages=relationshipMessages(history,'my next question');
 assert.equal(messages[0].role,'user');assert.equal(messages.at(-1).content,'my next question');
 assert.ok(messages.every(m=>m.content.length<=4000));assert.ok(messages.reduce((n,m)=>n+m.content.length,0)<=16000);
});
test('person validation rejects invalid dates, source mismatches and fabricated unknown-time charts',()=>{
  assert.equal(cleanPerson(person()).birth.time,'');
  assert.throws(()=>cleanPerson({...person(),source:'self'}),/INVALID_PERSON/);
  assert.throws(()=>cleanPerson({...person(),birth:{...person().birth,date:'2026-02-30'}}),/INVALID_BIRTH/);
  assert.throws(()=>cleanPerson({...person(),birth:{...person().birth,date:'2026-99-99'}}),/INVALID_BIRTH/);
  assert.throws(()=>cleanPerson({...person(),chart:{core:{type:'fake'}}}),/INVALID_CHART/);
  const anonymous=anonymousPerson({...person(),revision:1});
  assert.equal(anonymous.chart,null); assert.ok(!JSON.stringify(anonymous).includes('private observation'));assert.ok(!('nickname' in anonymous));
});
test('repository rejects a response arriving after account switch',async()=>{
  let resolve; const account={user:{id:A},client:{rpc:()=>new Promise(r=>{resolve=r;})}};
  const request=relationshipRepository(account).save(A,me,0,A,person(true));
  account.user={id:B};resolve({data:{id:me},error:null});await assert.rejects(request,/ACCOUNT_CHANGED/);
});
test('server context only reads selected owned pair and exact authorized excerpts',async()=>{
  const selection={selfId:me,personId:wife,selfRevision:1,personRevision:1,journal:[{id:other,excerpt:'selected words'}]};
  const rows=[{...person(true),id:me,user_id:A,revision:1},{...person(),id:wife,user_id:A,revision:1}];
  const calls=[];
  const fetchImpl=async(url,options)=>{calls.push({url,options});return Response.json(url.endsWith('/auth/v1/user')?{id:A}:url.includes('buer_people')?rows:[{id:other,user_id:A,body:'Only selected words for today'}]);};
  const settings={environment:{BUER_ACCOUNT_URL:'https://example.test',BUER_ACCOUNT_PUBLISHABLE_KEY:'public'},fetchImpl};
  const result=await loadRelationshipContext(selection,'Bearer test',settings);
  assert.deepEqual(result.selectedJournalExcerpts,['selected words']);assert.equal(result.me.chart,null);
  assert.ok(calls.every(c=>c.options.headers.Authorization==='Bearer test'));
  assert.ok(!JSON.stringify(result).includes('private observation'));
  await assert.rejects(loadRelationshipContext({...selection,journal:[{id:other,excerpt:'unselected private words'}]},'Bearer test',settings),/JOURNAL_CHANGED/);
  rows[1].user_id=B;await assert.rejects(loadRelationshipContext(selection,'Bearer test',settings),/PROFILES_CHANGED/);
  assert.throws(()=>validateRelationshipSelection({...selection,personId:me}),/INVALID_INPUT/);
  assert.throws(()=>validateConversation({mode:'relationship',messages:[{role:'user',content:'Help'}]}),/INVALID_INPUT/);
  assert.throws(()=>validateConversation({mode:'relationship',report:{Type:'Generator'},messages:[{role:'user',content:'Help'}]},result),/INVALID_INPUT/);
});
test('relationship SQL enforces two-owner isolation, CAS, identity, revisions, deletion and null validation',async()=>{
  const db=new PGlite();
  try{
    await db.exec(`create role anon;create role authenticated;create schema auth;
      create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema auth to anon,authenticated;
      insert into auth.users values('${A}'),('${B}');`);
    await db.exec(await readFile(new URL('../supabase/migrations/202610050002_relationships.sql',import.meta.url),'utf8'));
    await db.exec(await readFile(new URL('../supabase/migrations/202610060001_relationship_self_delete.sql',import.meta.url),'utf8'));
    const as=async owner=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${owner}',false);`);
    const save=(id,data,revision=0,mutation=A)=>db.query('select * from public.buer_save_person($1,$2,$3,$4)',[id,revision,mutation,data]);
    const chat=(own=me,partner=wife,rev=1)=>db.query('select * from public.buer_save_relationship_conversation($1,0,$2,$3,$4,$5,1,$6)',[thread,A,own,partner,rev,[{role:'user',content:'An event'}]]);
    await as(A);await save(me,person(true));await save(wife,person());
    const input={birthDate:'1990-01-01',birthTime:'12:00',timezone:'Asia/Shanghai',locationLabel:'Shanghai'};
    const result=await calculateHumanDesign({name:'QA',location:'Shanghai',year:1990,month:1,day:1,hour:12,minute:0,timezone:input.timezone,timeDisambiguation:'earlier'});
    const chart=await createHumanDesignProfileSnapshot({input,result});
    const withChart={...person(),birth:{certainty:'known',date:input.birthDate,time:input.birthTime,timezone:input.timezone,location:input.locationLabel},chart};
    assert.equal(cleanPerson(withChart).chart.core.type,chart.core.type);
    assert.equal(anonymousPerson(withChart).chart.type,chart.core.type);
    await save(other,withChart);
    await assert.rejects(save(other,{...withChart,birth:{...withChart.birth,date:'1990-01-02'}},1,B),/invalid_chart/);
    await db.query('select public.buer_delete_person($1,1,$2)',[other,B]);
    assert.equal((await save(me,person(true))).rows[0].revision,1);
    await assert.rejects(save('00000000-0000-4000-b000-000000000005',person(true)),/unique/);
    await assert.rejects(save(other,{...person(),birth:null}),/invalid_birth/);
    await assert.rejects(save(other,{...person(),chart:{core:{type:'fake'}}}),/invalid_birth/);
    await as(B);assert.equal((await db.query('select * from public.buer_people')).rows.length,0);
    await assert.rejects(save(me,person(true)),/profile_conflict/);
    await assert.rejects(chat(),/profiles_changed/);
    const outsider='00000000-0000-4000-b000-000000000004';await save(outsider,person());
    await as(A);await assert.rejects(chat(me,outsider),/profiles_changed/);
    await chat();assert.equal((await db.query('select * from public.buer_relationship_conversations')).rows.length,1);
    await as(B);assert.equal((await db.query('select * from public.buer_relationship_conversations')).rows.length,0);
    await as(A);await save(wife,{...person(),notes:'changed'},1,B);
    await assert.rejects(save(wife,person(),1,other),/profile_conflict/);
    await assert.rejects(chat(wife,me,2),/profiles_changed/);
    await assert.rejects(db.exec('update public.buer_people set nickname=\'x\''),/permission denied/);
    await db.query('select public.buer_delete_person($1,2,$2)',[wife,other]);
    assert.equal((await db.query('select * from public.buer_relationship_conversations')).rows.length,0);
    const deleted=(await db.query('select * from public.buer_people where id=$1',[wife])).rows[0];assert.equal(deleted.chart,null);assert.equal(deleted.notes,'');
    await db.query('select public.buer_delete_person($1,1,$2)',[me,B]);
    const deletedSelf=(await db.query('select * from public.buer_people where id=$1',[me])).rows[0];
    assert.ok(deletedSelf.deleted_at);assert.deepEqual(deletedSelf.birth,{});assert.equal(deletedSelf.nickname,'deleted');
    await db.query('select public.buer_delete_person($1,1,$2)',[me,B]);
    await save('00000000-0000-4000-b000-000000000006',person(true));
    await db.exec('reset role;set role anon');await assert.rejects(db.query('select * from public.buer_people'),/permission denied/);
    await db.exec(`reset role;delete from auth.users where id='${A}'`);
    assert.equal((await db.query('select * from public.buer_people where user_id=$1',[A])).rows.length,0);
  }finally{await db.close();}
});
