import {GROWTH_KEY,DOMAINS,QUESTIONS,readGrowth,saveGrowth,cleanGrowth,setGrowthAnswer,answeredCount,assessmentContext} from '../services/buer-growth.js';
import {readBuerEvents} from '../services/buer-conversation.js';
import {ensureAIConsent,chatAccess,showMembership} from './buer-membership.js';
import {renderAssistantText} from './buer-message-format.js';

const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderGrowthReport(element,content){
 element.replaceChildren();
 for(const line of String(content).split('\n')){
  if(!line.trim())continue;
  const heading=/^#{1,3}\s+/.test(line),list=/^[-*]\s+/.test(line);
  const node=document.createElement(heading?'h3':'p');
  let value=line.replace(/^#{1,3}\s+/,'');
  if(list){node.className='growth-report-item';value='• '+value.replace(/^[-*]\s+/,'');}
  renderAssistantText(node,value);element.append(node);
 }
}
export function initBuerGrowth({getLanguage,openHumanDesign,getReport}){
 const root=document.createElement('section');root.id='buerGrowth';root.className='growth-workspace';root.setAttribute('aria-label','Growth profile');document.querySelector('.shell').before(root);
 let state=readGrowth(localStorage),view='overview',editing=null,busy=false,controller=null,notice='';
 const zh=()=>getLanguage()==='zh',l=(cn,en)=>zh()?cn:en;
 const domainNames=()=>zh()?['心智','身体','关系与意义','事业']:['Mind','Body','Connection & meaning','Vocation'];
 function persist(){try{state=saveGrowth(localStorage,state);document.dispatchEvent(new Event('buer:growth-updated'));return true;}catch{notice=l('设备存储不可用。当前内容仅在本页保留，请先导出备份。','Device storage is unavailable. Export a backup before leaving this page.');const status=root.querySelector('#growthStatus');if(status)status.textContent=notice;return false;}}
 function open(next='overview'){view=busy?'assessment':next;document.body.dataset.workspace='growth';window.scrollTo({top:0,behavior:'instant'});render();root.querySelector('h1')?.focus({preventScroll:true});}
 const button=(id,cn,en,primary=false)=>`<button type="button" ${id?`id="${id}"`:""} class="growth-button${primary?' primary':''}">${l(cn,en)}</button>`;
 function render(){
 root.innerHTML=`<header class="growth-header"><p class="growth-eyebrow">BUER WITHIN / ${l('成长档案','GROWTH PROFILE')}</p><h1 tabindex="-1">${view==='assessment'?l('从四个领域，看见当下。','See your life from four angles.'):view==='stories'?l('你的来时路，值得被记住。','Your story matters.'):l('认识自己，走好下一步。','Know yourself. Take your next step.')}</h1><p>${l('理解你的节奏、看清眼前的事，让每一次行动都有回响。','Understand your rhythms, work through what matters and learn from each step.')}</p></header><nav class="growth-tabs" aria-label="${l('成长档案页面','Growth profile pages')}">${[['overview','成长路线','Your path'],['assessment','HUMAN 3.0','HUMAN 3.0'],['stories','我的经历','My story']].map(([id,cn,en])=>`<button type="button" data-growth-view="${id}" aria-current="${view===id?'page':'false'}">${l(cn,en)}</button>`).join('')}</nav><p id="growthStatus" role="status">${escape(notice)}</p><div id="growthContent"></div>`;
 root.querySelectorAll('[data-growth-view]').forEach(b=>b.onclick=()=>{if(!busy)open(b.dataset.growthView);});
 const content=root.querySelector('#growthContent');
 if(view==='overview')renderOverview(content);if(view==='assessment')renderAssessment(content);if(view==='stories')renderStories(content);
 }
 function renderOverview(content){
 const count=answeredCount(state),hasReport=Boolean(getReport());
 content.innerHTML=`<div class="growth-path"><article><span class="growth-index">01</span><div><small>${l('认识自己','KNOW YOURSELF')}</small><h2>${l('认识你的节奏','Understand your rhythms')}</h2><p>${l('填写出生信息，建立人类图。把解读作为观察线索，用真实经历验证。','Create your Human Design reading from birth details. Explore its ideas against your lived experience.')}</p><span class="growth-state">${hasReport?l('已有说明书','Reading available'):l('从这里开始','Start here')}</span></div>${button('growthHumanDesign',hasReport?'查看说明书':'填写人类图信息',hasReport?'View reading':'Create my reading')}</article><article><span class="growth-index">02</span><div><small>${l('明确行动 · 可以稍后','FIND DIRECTION · OPTIONAL')}</small><h2>${l('HUMAN 3.0 成长访谈','HUMAN 3.0 reflection')}</h2><p>${l('从心智、身体、关系与意义、事业出发，找到当下值得先解决的一件事。','Reflect on mind, body, connection and vocation. Find one problem worth working on first.')}</p><span class="growth-state">${count}/12 ${l('已回答','answered')}${state.skipped?' · '+l('已暂时跳过','Paused'):''}</span></div><div class="growth-stack">${button('growthAssessment',count?'继续访谈':'开始访谈',count?'Continue reflection':'Start reflection')}${button('growthSkip','暂时跳过','Do this later')}</div></article><article><span class="growth-index">03</span><div><small>${l('持续了解 · 随时补充','BUILD CONTEXT · ANY TIME')}</small><h2>${l('把来时路，慢慢说给我听','Bring your story with you')}</h2><p>${l('经历、转折、目标、限制与偏好。由你选择哪些内容供 AI 参考。','Experiences, turning points, goals, constraints and preferences. You choose what your coach can reference.')}</p><span class="growth-state">${state.stories.length} ${l('条经历','entries')}</span></div>${button('growthStories','补充我的经历','Add my story')}</article></div><section class="growth-actions"><div class="growth-section-title"><div><p class="growth-eyebrow">${l('把理解，变成行动','FROM INSIGHT TO ACTION')}</p><h2>${l('下一步，由你选择。','Choose your next step.')}</h2></div>${button('growthDiscuss','和教练聊聊','Talk to my coach')}</div><div id="growthActionList"></div><form id="growthActionForm" class="growth-action-form"><label>${l('我准备尝试的一件事','One thing I want to try')}<input id="growthActionTitle" maxlength="200" required placeholder="${l('例如：周三前与同事讨论一次分工','For example: discuss responsibilities with a colleague')}" /></label><div class="growth-form-row"><label>${l('什么时候回顾','Review date')}<input type="date" id="growthActionDue" required></label><label>${l('怎样算有进展','What would progress look like?')}<input id="growthActionMetric" maxlength="300" required placeholder="${l('一个可观察的变化','An observable change')}"></label></div><button class="growth-button primary" type="submit">${l('记下这个行动','Save this action')}</button></form></section><footer class="growth-footer"><p>${l('档案保存在当前设备。你可以随时导出或删除。','Your profile stays on this device. Export or delete it whenever you choose.')}</p>${button('growthExport','导出成长档案','Export profile')}${button('growthClear','清空成长档案','Clear profile')}</footer>`;
 content.querySelector('#growthHumanDesign').onclick=openHumanDesign;
 content.querySelector('#growthAssessment').onclick=()=>open('assessment');content.querySelector('#growthStories').onclick=()=>open('stories');
 content.querySelector('#growthSkip').onclick=()=>{state.skipped=true;persist();open('stories');};
 content.querySelector('#growthDiscuss').onclick=()=>document.querySelector('.rail-item[data-home]').click();
 renderActions(content.querySelector('#growthActionList'));
 content.querySelector('#growthActionForm').onsubmit=e=>{e.preventDefault();const title=content.querySelector('#growthActionTitle').value.trim(),metric=content.querySelector('#growthActionMetric').value.trim();if(!title||!metric)return;if(state.actions.length>=100){notice=l('已达到 100 个行动，请先导出并整理。','You have 100 actions. Export and organize them first.');render();return;}state.actions.unshift({id:crypto.randomUUID(),title,metric,due:content.querySelector('#growthActionDue').value,done:false,reflection:''});persist();render();};
 content.querySelector('#growthExport').onclick=async()=>{try{const json=JSON.stringify(state,null,2);if(globalThis.Capacitor?.isNativePlatform?.()){const plugin=globalThis.Capacitor.Plugins?.PlutoNative||globalThis.Capacitor.registerPlugin('PlutoNative');await plugin.exportGrowthProfile({json});}else{const blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='buer-growth-profile.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch{notice=l('导出未完成，请重试。','Export did not complete. Please try again.');render();}};
 content.querySelector('#growthClear').onclick=()=>confirmAction(l('清空成长档案？','Clear your growth profile?'),l('将删除本机访谈、经历、行动和复盘。不会删除人类图与对话，也无法撤回已发送给 AI 的内容。','This removes local reflections, stories, actions and reviews. Readings and conversations stay. It cannot recall information already sent to AI.'),()=>{state=cleanGrowth();if(persist())notice=l('成长档案已清空。','Growth profile cleared.');render();});
 }
 function renderActions(list){
 if(!state.actions.length){list.innerHTML=`<p class="growth-empty">${l('不用一次改变整个人生。先选择一个小而具体的尝试。','You do not need to change everything at once. Start with one small, specific experiment.')}</p>`;return;}
 list.replaceChildren();for(const action of state.actions){const card=document.createElement('article');card.className='growth-action';card.innerHTML=`<label class="growth-check"><input type="checkbox" ${action.done?'checked':''}><strong>${escape(action.title)}</strong></label><p>${escape(action.due)} · ${escape(action.metric)}</p><label>${l('复盘：发生了什么，下次怎么调整？','Review: what happened, and what would you adjust?')}<textarea rows="2" maxlength="1200">${escape(action.reflection)}</textarea></label><div class="growth-action-controls"><button type="button" class="growth-text-button growth-action-discuss">${l('与教练复盘','Reflect with my coach')}</button><button type="button" class="growth-text-button growth-action-delete">${l('删除行动','Delete action')}</button></div>`;card.querySelector('input').onchange=e=>{action.done=e.target.checked;persistWithoutReplacingActions();};card.querySelector('textarea').oninput=e=>{action.reflection=e.target.value;persistWithoutReplacingActions();};card.querySelector('.growth-action-discuss').onclick=()=>{document.dispatchEvent(new CustomEvent('buer:growth-question',{detail:{question:l('请陪我复盘这个行动，帮我确定一个调整：','Help me review this action and choose one adjustment:')+'\n'+action.title+'\n'+l('进展标准：','Progress criterion: ')+action.metric+'\n'+l('已完成：','Completed: ')+(action.done?l('是','yes'):l('否','no'))+'\n'+l('我的观察：','My observations: ')+action.reflection}}));};card.querySelector('.growth-action-delete').onclick=()=>confirmAction(l('删除这个行动及复盘？','Delete this action and its review?'),'',()=>{state.actions=state.actions.filter(x=>x.id!==action.id);persist();render();});list.append(card);}
 }
 // Keep live form closures attached to the same objects while autosaving.
 function persistWithoutReplacingActions(){try{saveGrowth(localStorage,state);document.dispatchEvent(new Event('buer:growth-updated'));}catch{notice=l('未能保存到设备，请导出备份。','Could not save to device. Please export a backup.');root.querySelector('#growthStatus').textContent=notice;}}
 function renderAssessment(content){
 const count=answeredCount(state),q=QUESTIONS[state.cursor],domain=DOMAINS.indexOf(q.domain);
 content.innerHTML=`<div class="growth-assessment-layout"><aside class="growth-domains">${DOMAINS.map((d,i)=>`<button type="button" data-domain="${i}" aria-current="${domain===i?'step':'false'}"><span>0${i+1}</span>${domainNames()[i]}<small>${QUESTIONS.filter(q=>q.domain===d&&state.answers[q.id]?.trim()).length}/3</small></button>`).join('')}<p>${l('12 个基础问题，一次一个。随时离开，下次接着回答。','12 starting questions, one at a time. Leave whenever you need and resume later.')}</p><a href="https://thedankoe.com/letters/human-3-0-a-map-to-reach-the-top-1/" target="_blank" rel="noopener noreferrer">${l('框架来源：Dan Koe','Framework: Dan Koe')} ↗</a></aside><section class="growth-question-card"><p class="growth-eyebrow">${domainNames()[domain]} · ${state.cursor+1} / 12</p><h2>${escape(q[zh()?'zh':'en'])}</h2><label class="sr-only" for="growthAnswer">${l('你的回答','Your answer')}</label><textarea id="growthAnswer" rows="5" maxlength="1200" placeholder="${l('从一件真实发生的事说起…','Start with something that actually happened…')}">${escape(state.answers[q.id])}</textarea><small>${l('回答修改后，旧的 AI 行动指南会失效；原始经历不会被 AI 改写。','Editing an answer clears the previous AI guide. AI never rewrites your original answers.')}</small><div class="growth-question-nav">${button('growthPrevious','上一题','Previous')}${button('growthNext',state.cursor===11?'回到成长路线':'保存并继续',state.cursor===11?'Back to your path':'Save & continue',true)}</div><div class="growth-assessment-generate"><p>${count}/12 ${l('已回答。完成基础访谈后，可生成一份行动指南。','answered. Complete the reflection to generate your action guide.')}</p>${button('growthGenerate',busy?'正在整理…':state.report?'重新生成行动指南':'生成我的行动指南',busy?'Preparing…':state.report?'Regenerate my guide':'Generate my action guide',true)}<small>${l('生成时将这 12 个回答发送给 DeepSeek；完成的指南计为 1 条 AI 回复。','Generation sends these 12 answers to DeepSeek. A completed guide counts as one AI reply.')}</small>${busy?button('growthStop','停止生成','Stop generating'):''}<label class="growth-check"><input type="checkbox" id="growthShareAssessment" ${state.shareAssessment?'checked':''}>${l('允许日常对话参考这些回答（还需在对话中勾选成长档案）','Allow these answers as chat context (also enable profile context in chat)')}</label></div></section></div><section class="growth-report" ${state.report?'':'hidden'}><p class="growth-eyebrow">${l('AI 行动指南 · 基于你的回答','AI ACTION GUIDE · BASED ON YOUR ANSWERS')}</p><div id="growthReportText"></div>${button('growthPlanAction','选择我的下一步行动','Choose my next action',true)}</section><p class="growth-method-note">${l('这是参考 HUMAN 3.0 四领域框架的自我反思访谈，不是科学测量或心理诊断，也不代表 Dan Koe 官方测评。结论需要在生活中验证。','This self-reflection draws on the HUMAN 3.0 four-domain framework. It is not a validated measurement, diagnosis or official Dan Koe assessment. Test its ideas against lived experience.')}</p>`;
 content.querySelectorAll('[data-domain]').forEach(b=>b.onclick=()=>{state.cursor=Number(b.dataset.domain)*3;persist();render();});
 content.querySelector('#growthAnswer').oninput=e=>{state=setGrowthAnswer(state,q.id,e.target.value);persist();content.querySelector('.growth-report').hidden=true;const currentCount=answeredCount(state);content.querySelector('#growthGenerate').disabled=currentCount!==12;content.querySelector('#growthGenerate').textContent=l('生成我的行动指南','Generate my action guide');content.querySelector('.growth-assessment-generate>p').textContent=`${currentCount}/12 `+l('已回答。完成基础访谈后，可生成一份行动指南。','answered. Complete the reflection to generate your action guide.');content.querySelector(`[data-domain="${domain}"] small`).textContent=QUESTIONS.filter(item=>item.domain===q.domain&&state.answers[item.id]?.trim()).length+'/3';};
 content.querySelector('#growthPrevious').disabled=state.cursor===0;content.querySelector('#growthPrevious').onclick=()=>{state.cursor--;persist();render();};
 content.querySelector('#growthNext').onclick=()=>{if(state.cursor===11)open();else{state.cursor++;persist();render();root.querySelector('.growth-question-card').scrollIntoView({block:'start',behavior:'smooth'});root.querySelector('#growthAnswer').focus({preventScroll:true});}};
 content.querySelector('#growthShareAssessment').onchange=e=>{state.shareAssessment=e.target.checked;persist();};
 content.querySelector('#growthGenerate').disabled=count!==12||busy;content.querySelector('#growthGenerate').onclick=generate;
 content.querySelector('#growthStop')?.addEventListener('click',()=>controller?.abort());
 renderGrowthReport(content.querySelector('#growthReportText'),state.report);
 content.querySelector('#growthPlanAction').onclick=()=>{open();root.querySelector('#growthActionTitle').focus();};
 if(busy)content.querySelectorAll('textarea,input,[data-domain],#growthNext,#growthPrevious').forEach(x=>x.disabled=true);
 }
 async function generate(){
 if(busy||answeredCount(state)!==12)return;
 if(!await ensureAIConsent()||busy)return;
 busy=true;notice='';controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),110000);render();let result='';
 try{if(globalThis.PLUTO_CONFIG?.buerChatEnabled===false)throw Error('AI_NOT_CONFIGURED');const response=await fetch(`${(globalThis.PLUTO_CONFIG?.apiBaseUrl||'').replace(/\/$/,'')}/v1/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'growth-assessment',messages:[{role:'user',content:l('请根据我的四领域回答，整理我的成长行动指南。用中文回应。','Create my growth action guide from my four-domain answers. Respond in English.')}],growth:{answers:assessmentContext(state),stories:[]},...await chatAccess()}),signal:controller.signal});if(!response.ok){const data=await response.json().catch(()=>({}));throw Error(data.error||'AI_UNAVAILABLE');}await readBuerEvents(response.body,(type,data)=>{if(type==='delta'){result+=data.text;const report=root.querySelector('.growth-report');if(report){report.hidden=false;renderGrowthReport(root.querySelector('#growthReportText'),result);}}});state.report=result;state.reportDate=new Date().toISOString();if(persist())notice=l('行动指南已保存。选一个你愿意尝试的行动，并设定回顾日期。','Guide saved. Choose one action and set a review date.');}
 catch(error){if(error.message==='DAILY_LIMIT')showMembership();notice=error.message==='DAILY_LIMIT'?l('今日免费额度已用完。回答已保存，可明天继续或开通会员。','Your free allowance is used. Answers are saved; continue tomorrow or subscribe.'):controller.signal.aborted?l('已停止，回答仍保留。','Stopped. Your answers are kept.'):l('暂时无法生成，回答已保留。请稍后重试。','Could not generate a guide. Your answers are kept. Please try again.');}
 finally{clearTimeout(timeout);busy=false;controller=null;render();}
 }
 function renderStories(content){
 const entry=state.stories.find(x=>x.id===editing);
 content.innerHTML=`<div class="growth-stories-layout"><section><p>${l('记录重要经历、转折、眼前目标和现实限制。无需一次讲完，也不需要交出全部隐私。','Record turning points, current goals and real-world constraints. You can build this gradually, sharing only what you choose.')}</p><form id="growthStoryForm" class="growth-story-form"><label>${l('这段经历的名字','Give this story a title')}<input id="growthStoryTitle" maxlength="100" required value="${escape(entry?.title)}" placeholder="${l('例如：一次职业转折','For example: a career turning point')}"></label><label>${l('发生了什么，对你有什么影响？','What happened, and how did it affect you?')}<textarea id="growthStoryBody" rows="7" maxlength="4000" required>${escape(entry?.body)}</textarea></label><label class="growth-check"><input type="checkbox" id="growthStoryPermission" ${entry?.useAI?'checked':''}>${l('允许 AI 参考这条经历','Allow AI to reference this entry')}</label><small>${l('仅在你勾选对话中的“结合成长档案”并发送问题时，才会发送相关经历（最多 4 条，每条前 2000 字符）。','Only sent when you enable profile context and send a message: up to 4 relevant entries, the first 2,000 characters each.')}</small><div class="growth-story-controls"><button class="growth-button primary" type="submit">${entry?l('保存修改','Save changes'):l('保存这段经历','Save this story')}</button><label class="growth-file-label">${l('导入 TXT / Markdown','Import TXT / Markdown')}<input type="file" id="growthStoryImport" accept=".txt,.md,text/plain,text/markdown"></label>${entry?button('growthCancelEdit','取消编辑','Cancel edit'):''}</div><small>${l('每条最多 4000 字符、总计 100 条；长文请分段保存。保存后才能用于 AI。','Up to 4,000 characters per entry and 100 entries. Split long documents into sections. Save before using with AI.')}</small></form></section><section><p class="growth-eyebrow">${l('我的经历','MY STORY')} / ${state.stories.length}</p><div id="growthStoryList"></div></section></div>`;
 content.querySelector('#growthCancelEdit')?.addEventListener('click',()=>{editing=null;render();});
 content.querySelector('#growthStoryImport').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>24000||!(/\.(txt|md)$/i.test(file.name))){notice=l('请导入不超过 24 KB 的 TXT 或 Markdown 文件。','Choose a TXT or Markdown file up to 24 KB.');root.querySelector('#growthStatus').textContent=notice;return;}try{const value=await file.text();if(value.length>4000){notice=l('文件超过 4000 字符。请分段粘贴，原内容未被替换。','This file exceeds 4,000 characters. Paste it in sections; existing text was kept.');root.querySelector('#growthStatus').textContent=notice;return;}content.querySelector('#growthStoryBody').value=value;if(!content.querySelector('#growthStoryTitle').value)content.querySelector('#growthStoryTitle').value=file.name.slice(0,100);}catch{root.querySelector('#growthStatus').textContent=l('无法读取文件，请直接粘贴文字。','Could not read the file. Paste its text instead.');}};
 content.querySelector('#growthStoryForm').onsubmit=e=>{e.preventDefault();const title=content.querySelector('#growthStoryTitle').value.trim(),body=content.querySelector('#growthStoryBody').value.trim();if(!title||!body)return;if(!entry&&state.stories.length>=100){root.querySelector('#growthStatus').textContent=l('已达 100 条，请先导出并整理。','You have 100 entries. Export and organize them first.');return;}const saved={id:entry?.id||crypto.randomUUID(),title,body,useAI:content.querySelector('#growthStoryPermission').checked,date:new Date().toISOString()};state.stories=[saved,...state.stories.filter(x=>x.id!==saved.id)];editing=null;persist();render();};
 const list=content.querySelector('#growthStoryList');if(!state.stories.length)list.innerHTML=`<p class="growth-empty">${l('先从一件让你成为今天的自己的事开始。','Start with one experience that helped shape who you are today.')}</p>`;
 for(const story of state.stories){const item=document.createElement('article');item.className='growth-story';item.innerHTML=`<small>${story.useAI?l('允许 AI 参考','Available as AI context'):l('仅自己保存','Private to this device')}</small><h3>${escape(story.title)}</h3><p>${escape(story.body.slice(0,240))}${story.body.length>240?'…':''}</p><div>${button('','编辑','Edit')}${button('','删除','Delete')}</div>`;const [edit,remove]=item.querySelectorAll('button');edit.onclick=()=>{editing=story.id;render();root.querySelector('#growthStoryTitle').focus();};remove.onclick=()=>confirmAction(l('删除这条经历？','Delete this story?'),l('本机删除无法撤回已发送的 AI 请求。','Local deletion cannot recall previous AI requests.'),()=>{state.stories=state.stories.filter(x=>x.id!==story.id);if(editing===story.id)editing=null;persist();render();});list.append(item);}
 }
 function confirmAction(title,description,action){const dialog=document.createElement('dialog');dialog.className='buer-membership growth-confirm';dialog.innerHTML=`<h2>${escape(title)}</h2><p>${escape(description)}</p>${button('','取消','Cancel')}${button('','确认删除','Delete',true)}`;const [cancel,yes]=dialog.querySelectorAll('button');cancel.onclick=()=>dialog.close();yes.onclick=()=>{dialog.close();action();};dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();cancel.focus();}
 document.addEventListener('buer:language',()=>{if(!busy)render();});
 document.querySelectorAll('[data-growth]').forEach(b=>b.onclick=()=>open());
 // Sources remain user-controlled; no automatic network requests are made on entry.
 render();return {open};
}
